### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by aa25g15** [khalyomede/gulp-sharp-responsive#6]
### In Examples:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/26576978/174581641-89b16ad4-ee16-42ba-93f4-5bc384937a91.png">

### Typo:
`require("sharp-responsive");`

### Correction:
`require('gulp-sharp-responsive');`

**Comment by khalyomede** [comment]
Hello @aa25g15, good catch thanks! If you whish to contribute, feel free to make a PR for that, it will be greatly appreciated :)
