### ISSUE TITLE
Package updates?

### ISSUE THREAD

**Issue by aidanmcdonagh22** [khalyomede/gulp-sharp-responsive#7]
Hi there, any chance you can bump up the package versions? Happy to do this myself if it's either and make an MR/PR

**Comment by khalyomede** [comment]
Hey 👋 going to do it tonight, thanks for letting me know 🙏

**Comment by khalyomede** [comment]
I just published v0.4.0 with an update of sharp and image-size, let me know if it is okay for you

**Comment by aidanmcdonagh22** [comment]
Oh nice, thank you, will update and let you know how it goes! Appreciate it

**Comment by khalyomede** [comment]
Closing it after no further requests is received, feel free to re-open it if you need it.
